### PR TITLE
08 get seconds today

### PR DESCRIPTION
**Pull request by dianaamfr**

### CODE REVIEW

**Comment by dianaamfr** [comment]
image
Acho que faltaram os inputs aqui.
Mudei as tabelas das variáveis sem ser o m, please check

**Review by dianaamfr — COMMENTED** [review]
Missing description, I'm going to add it [DONE]

**Comment by Jumaruba** [comment]
Blocks after [try catch are not executed](https://stackoverflow.com/questions/4691962/why-use-finally-instead-of-code-after-catch) unless there is a `finally` block. Thus, I think that it should have an *end circle*  after block 5. 
image

**Comment by Jumaruba** [comment]
Greeat!

**Pull request merged**
